preset: psr2

disabled:
  - psr2_braces # keep newlines in closures

enabled:
  - alpha_ordered_imports
  - blank_line_after_opening_tag
  - concat_with_spaces
  - linebreak_after_opening_tag
  - lowercase_cast
  - method_separation
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_namespace_whitespace
  - no_short_bool_cast
  - no_short_echo_tag
  - no_whitespace_in_blank_line
  - print_to_echo
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
